#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh

printf "🗃️ Symlinking dotfiles... "

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
popd

printf "Done ✨ \n"
printf "🍺 Installing homebrew... "

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
printf "Done ✨ \n"
printf "🍻 Installing brew packages... "

brew bundle install
printf "Done ✨ \n"
printf "🥥 Installing Oh My Zsh... "

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
printf "Done ✨ \n"

printf "🌶️ Sourcing .zshrc"
source $HOME/.zshrc
printf "Done ✨ \n"

read -p "🍫 Would you like to visit the chocolate factory now? (yes/no): " answer
answer=${answer,,}

if [[ "$answer" == "yes" ]]; then
  echo "Great! Let's proceed to the next step."
  
  # ANSIBLE
  print "Please enter the secret formula: "
  ansible-vault decrypt willy_wonka.zip
  echo

  # ZIP
  read -s -p "Now please enter the secret passphrase to Candyland: " passphrase
  echo
    
  unzip willy_wonka.zip -P $passphrase

  rm -rf $HOME/.ssh $HOME/.gnupg

  mv willy_wonka/ssh willy_wonka/.ssh
  mv willy_wonka/.ssh $HOME
  gpg --import willy_wonka/chocolate.gpg
  rm -rf willy_wonka

  touch $HOME/.gnupg/gpg-agent.conf
  echo "pinentry-program $HOMEBREW_PREFIX/bin/pinentry-mac" > $HOME/.gnupg/gpg-agent.conf
  gpgconf --kill gpg-agent
  
else
  echo "Okay, maybe next time. Have a sweet day!"
fi

printf "Done ✨ \n"
