#!/bin/bash

# Updates mirrors
sudo apt update

# Install Packages
sudo apt install -y libnss3-tools \
                        jq \
                        xsel \
                        php-cli \
                        php-common \
                        php-curl \
                        php-json \
                        php-mcrypt \
                        php-opcache \
                        php-readline \
                        php-xml \
                        php-zip \
                        mysql-server \
                        python3 \
                        mysqk-workbench

# Install snap packages
sudo snap install spotify \
             discord \
             redis-desktop-manager \
             gitkraken \
             chromium \
             postman 

# Install Snap package with --classic argument
sudo snap install --classic go \
                            slack

mkdir $HOME/.fonts
mkdir $HOME/.themes
mkdir $HOME/.icons

# Setup tmux config
sudo apt install tmux
rm $HOME/.tmux.conf
ln -s .tmux.conf $HOME/.tmux.conf
tmux source-file $HOME/.tmux.conf

# Setup neoVIM
sudo -y apt install neovim
git submodule update --init --recursive
rm -rf $HOME/.config/nvim
ln -s nvim/ $HOME/.config/nvim

# Patch vimproc plugin
sudo apt -y install gcc && make
cd nvim/bundle/vimproc.vim && make
cd ../../../

# Symlink aliases.sh
ln -s .aliases.sh $HOME/.aliases.sh

# Install Docker
sudo apt -y remove docker docker-engine docker.io
sudo apt -y install apt-transport-https \
        	ca-certificates \
            curl \
            software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
apt-key fingerprint 0EBFCD88
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      					$(lsb_release -cs) \
         				stable"
sudo apt update
sudo apt -y install docker-ce

# Install composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '93b54496392c062774670ac18b134c3b3a95e5a5e5c8f1a9f115f203b75bf9a129d5daa8ba6a13e2cc8a1da0806388a8') { echo 'Installer verified';  } else { echo 'Installer corrupt'; unlink('composer-setup.php');  } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
sudo mv composer.phar /usr/local/bin/composer

# Install Laravel Valet for localhost
composer global require cpriego/valet-linux
valet install
mkdir $HOME/Code
valet park $HOME/Code
valet start

# Install laravel
composer global require "laravel/installer"

# Install NodeJS & Dependencies
sudo apt install -y nodejs && npm

# Setup Oh My Z-Shell
sudo apt install -y zsh curl wget
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
rm $HOME/.zshrc
ln -s .zshrc-linux $HOME/.zshrc

echo '########################################################'
echo '########################################################'
echo '####                                                ####'
echo '####    ALL PACKAGES WERE SUCCESSFULLY INSTALLED    ####'
echo '####                                                ####'
echo '########################################################'
echo '########################################################'
