#!/usr/bin/env zsh

# Backup old .zshrc
mv $HOME/.zshrc $HOME/.zshrc.old

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,configs,iterm,karabiner,nvim,secrets,workspacify"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
