#!/usr/bin/env zsh

printf "💻 Preparing environemnt... "

if [[ -z $STOW_FOLDERS ]]; then
    current_directory=$(pwd)
    STOW_FOLDERS=$(find "$current_directory" -mindepth 1 -maxdepth 1 -type d ! -name ".git" -exec basename {} \; | awk 'NR>1 {print ","} {print}' | tr -d '\n')
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

printf "Done ✨ \n"
printf "👾 Initiating install process"

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
