#!/bin/bash
GREEN='\e[32m'
printf "${GREEN}"

# Symlink
printf "Symlinking config files \n"
./symlink

# Nord GTK Theme
printf "Installing GTK Theme \n"
mkdir -p $HOME/.themes
rm -rf $HOME/.themes/Nordic
cp -R Nordic $HOME/.themes/

# Nord Gnome Terminal Theme
printf "Installing Gnome Terminal Theme \n"
./nord-gnome-terminal/src/nord.sh
gconftool-2 --set --type string /apps/gnome-terminal/global/default_profile Nord

